/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccessKeysRouteImport } from './routes/access-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessKeysRoute = AccessKeysRouteImport.update({
  id: '/access-keys',
  path: '/access-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-keys': typeof AccessKeysRoute
  '/analytics': typeof AnalyticsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/my-team': typeof MyTeamRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/users': typeof UsersRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-keys': typeof AccessKeysRoute
  '/analytics': typeof AnalyticsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/my-team': typeof MyTeamRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/users': typeof UsersRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-keys': typeof AccessKeysRoute
  '/analytics': typeof AnalyticsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/my-team': typeof MyTeamRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/users': typeof UsersRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-keys'
    | '/analytics'
    | '/leads'
    | '/login'
    | '/my-team'
    | '/notifications'
    | '/offers'
    | '/settings'
    | '/teams'
    | '/users'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-keys'
    | '/analytics'
    | '/leads'
    | '/login'
    | '/my-team'
    | '/notifications'
    | '/offers'
    | '/settings'
    | '/teams'
    | '/users'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/access-keys'
    | '/analytics'
    | '/leads'
    | '/login'
    | '/my-team'
    | '/notifications'
    | '/offers'
    | '/settings'
    | '/teams'
    | '/users'
    | '/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessKeysRoute: typeof AccessKeysRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MyTeamRoute: typeof MyTeamRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-keys': {
      id: '/access-keys'
      path: '/access-keys'
      fullPath: '/access-keys'
      preLoaderRoute: typeof AccessKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
  }
}

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessKeysRoute: AccessKeysRoute,
  AnalyticsRoute: AnalyticsRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MyTeamRoute: MyTeamRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
